services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongo:
    image: mongo:8
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -sharedDb
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  pg_data:
  mongo_data:
  dynamodb_data:
