export const DBGEN_DIR = new URL("../tpc-h/dbgen/", import.meta.url);

// Keeping this specific order because of foreign key constraints
export const TABLES = [
	"region",
	"nation",
	"supplier",
	"partsupp",
	"part",
	"customer",
	"orders",
	"lineitem",
] as const satisfies string[];

// biome-ignore format:
export const COLUMNS = {
	region: [
		"R_REGIONKEY",
		"R_NAME",
		"R_COMMENT",
	] as const,
	nation: [ 
		"N_NATIONKEY",
		"N_NAME",
		"N_REGIONKEY",
		"N_COMMENT",
	] as const,
	supplier: [
		"S_SUPPKEY",
		"S_NAME",
		"S_ADDRESS",
		"S_NATIONKEY",
		"S_PHONE",
		"S_ACCTBAL",
		"S_COMMENT",
	] as const,
	partsupp: [
		"PS_PARTKEY",
		"PS_SUPPKEY",
		"PS_AVAILQTY",
		"PS_SUPPLYCOST",
		"PS_COMMENT",
	] as const,
	part: [
		"P_PARTKEY",
		"P_NAME",
		"P_MFGR",
		"P_BRAND",
		"P_TYPE",
		"P_SIZE",
		"P_CONTAINER",
		"P_RETAILPRICE",
		"P_COMMENT",
	] as const,
	customer: [
		"C_CUSTKEY",
		"C_NAME",
		"C_ADDRESS",
		"C_NATIONKEY",
		"C_PHONE",
		"C_ACCTBAL",
		"C_MKTSEGMENT",
		"C_COMMENT",
	] as const,
	orders: [
		"O_ORDERKEY",
		"O_CUSTKEY",
		"O_ORDERSTATUS",
		"O_TOTALPRICE",
		"O_ORDERDATE",
		"O_ORDERPRIORITY",
		"O_CLERK",
		"O_SHIPPRIORITY",
		"O_COMMENT",
	] as const,
	lineitem: [
		"L_ORDERKEY",
		"L_PARTKEY",
		"L_SUPPKEY",
		"L_LINENUMBER",
		"L_QUANTITY",
		"L_EXTENDEDPRICE",
		"L_DISCOUNT",
		"L_TAX",
		"L_RETURNFLAG",
		"L_LINESTATUS",
		"L_SHIPDATE",
		"L_COMMITDATE",
		"L_RECEIPTDATE",
		"L_SHIPINSTRUCT",
		"L_SHIPMODE",
		"L_COMMENT",
	] as const,
} satisfies Record<(typeof TABLES)[number], string[]>;
